// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220606220233_EmployeeMigaration")]
    partial class EmployeeMigaration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Workday", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Workdays");
                });

            modelBuilder.Entity("Domain.WorkdayEmployee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkdayId")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeId", "WorkdayId");

                    b.HasIndex("WorkdayId");

                    b.ToTable("WorkdayEmployees");
                });

            modelBuilder.Entity("Domain.WorkdayEmployee", b =>
                {
                    b.HasOne("Domain.Employee", "Employee")
                        .WithMany("WorkdayEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Workday", "Workday")
                        .WithMany("WorkdayEmployees")
                        .HasForeignKey("WorkdayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Workday");
                });

            modelBuilder.Entity("Domain.Employee", b =>
                {
                    b.Navigation("WorkdayEmployees");
                });

            modelBuilder.Entity("Domain.Workday", b =>
                {
                    b.Navigation("WorkdayEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
